// Copyright (c) 2026 Geramy Loveless DBA Nexus Projects.
// Author: Geramy Loveless <support@nexus-projects.ai>
// Licensed under the Sustainable Use License. See LICENSE.md.

import 'dart:convert';

import 'package:drift/drift.dart' show Value;
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'package:nexus_projects_client/features/agents/agent_role.dart';
import 'package:nexus_projects_client/features/agents/agent_tool_permissions.dart';
import 'package:nexus_projects_client/infrastructure/database/nexus_database.dart';

/// Seeds initial data and guarantees the built-in "Default" client always
/// exists. With integer auto-increment PKs we let the DB assign ids; on a fresh
/// database the Default client becomes client_pk = 1.
///
/// We intentionally do NOT seed a sample project or tasks: the first-run
/// onboarding wizard walks the user through creating their real first project
/// (and picking an agent pack), so a fresh install starts clean instead of with
/// a confusing placeholder project.
Future<void> seedInitialData(NexusDatabase db) async {
  // Configurable setup-interview flows are global + idempotent — seed them
  // every launch (independent of the Default-client check below) so new built-in
  // flows (e.g. new IVR sub-categories) appear without a DB reset.
  try {
    await db.seedSetupFlows();
  } catch (e) {
    debugPrint('Seeder: setup flows warning (non-fatal): $e');
  }

  // Adaptive scoped-vocabulary tree (industries → sub-axes → scoped
  // objectives/features/libraries + platform stacks), bundled as an asset and
  // generated by deep research. Idempotent per-industry; safe every launch.
  try {
    await _seedScopedVocab(db);
  } catch (e) {
    debugPrint('Seeder: scoped vocab warning (non-fatal): $e');
  }

  await _maybeCreateDefaults(db);

  // Repair tool permissions on already-seeded personas. The Project Manager and
  // Coordinator must always be able to author user stories, but older seeds (and
  // installs on other machines) baked a default-deny map that blocked the story
  // tools because no skill bundle included them. Idempotent: only writes when a
  // story tool isn't already granted.
  try {
    await _grantStoryToolsToManagers(db);
  } catch (e) {
    debugPrint('Seeder: story-permission reconcile warning (non-fatal): $e');
  }
}

/// Ensures every Project Manager / Coordinator persona grants the full set of
/// user-story tools, repairing personas seeded before `story-authoring` existed
/// (their stored configJson explicitly denies these tools).
Future<void> _grantStoryToolsToManagers(NexusDatabase db) async {
  // Source of truth for the story tools — kept in sync with the catalog instead
  // of a hand-copied list.
  final storyTools = [
    for (final s in kCoordinatorToolSpecs)
      if (s.category == 'Stories') s.name,
  ];
  if (storyTools.isEmpty) return;

  for (final p in await db.getAllAgentPersonas()) {
    final role = agentRoleFromKey(p.title);
    if (role != AgentRole.projectManager && role != AgentRole.coordinator) {
      continue;
    }
    final perms = AgentToolPermissions.fromConfigJson(p.configJson);
    final needs = storyTools.any((t) => perms.permFor(t) != ToolPerm.grant);
    if (!needs) continue;

    // Preserve every existing override; only force the story tools to grant.
    final merged = Map<String, ToolPerm>.from(perms.overrides);
    for (final t in storyTools) {
      merged[t] = ToolPerm.grant;
    }
    final newJson = AgentToolPermissions.writeIntoConfigJson(
      p.configJson,
      merged,
    );
    await db.updateAgentPersona(
      p.toCompanion(true).copyWith(configJson: Value(newJson)),
    );
  }
}

/// Bundled scoped-vocabulary catalog version. BUMP THIS whenever
/// `assets/setup/scoped_vocab.json` is regenerated so existing installs reconcile
/// (insert new industries, update changed ones) on next launch.
const int _scopedVocabVersion = 1;

/// Load the bundled scoped-vocabulary catalog and reconcile it into the DB.
/// Version-gated: if the stored catalog version already matches the bundled one,
/// this returns immediately WITHOUT loading/parsing the (large) asset — so an
/// unchanged launch does no work. On first seed (version null) or a bumped
/// catalog, it inserts new records and updates existing ones. Empty/missing
/// asset is a no-op (the interview falls back to generic flow suggestions).
Future<void> _seedScopedVocab(NexusDatabase db) async {
  if (await db.scopedCatalogVersion() == _scopedVocabVersion) return;
  String raw;
  try {
    raw = await rootBundle.loadString('assets/setup/scoped_vocab.json');
  } catch (_) {
    return; // asset not bundled
  }
  if (raw.trim().isEmpty) return;
  final decoded = jsonDecode(raw);
  if (decoded is! List || decoded.isEmpty) return;
  await db.seedSetupScopes(decoded, version: _scopedVocabVersion);
}

Future<void> _maybeCreateDefaults(NexusDatabase db) async {
  final existingDefault = await db.getDefaultClient();
  if (existingDefault != null) return; // Already have a Default client.

  try {
    // Seeds the Default client + a Local Lemonade server + skill prefabs + the
    // default agent pack (Application Development).
    await db.createClientWithDefaults(name: 'Default', isDefault: true);
  } catch (e) {
    debugPrint('Seeder: could not ensure Default client (non-fatal): $e');
  }
}
