// Copyright (c) 2026 Geramy Loveless DBA Nexus Projects.
// Author: Geramy Loveless <support@nexus-projects.ai>
// Licensed under the Sustainable Use License. See LICENSE.md.

import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'package:nexus_projects_client/infrastructure/database/nexus_database.dart';

/// Seeds initial data and guarantees the built-in "Default" client always
/// exists. With integer auto-increment PKs we let the DB assign ids; on a fresh
/// database the Default client becomes client_pk = 1.
///
/// We intentionally do NOT seed a sample project or tasks: the first-run
/// onboarding wizard walks the user through creating their real first project
/// (and picking an agent pack), so a fresh install starts clean instead of with
/// a confusing placeholder project.
Future<void> seedInitialData(NexusDatabase db) async {
  // Configurable setup-interview flows are global + idempotent — seed them
  // every launch (independent of the Default-client check below) so new built-in
  // flows (e.g. new IVR sub-categories) appear without a DB reset.
  try {
    await db.seedSetupFlows();
  } catch (e) {
    debugPrint('Seeder: setup flows warning (non-fatal): $e');
  }

  // Adaptive scoped-vocabulary tree (industries → sub-axes → scoped
  // objectives/features/libraries + platform stacks), bundled as an asset and
  // generated by deep research. Idempotent per-industry; safe every launch.
  try {
    await _seedScopedVocab(db);
  } catch (e) {
    debugPrint('Seeder: scoped vocab warning (non-fatal): $e');
  }

  await _maybeCreateDefaults(db);
}

/// Load the bundled scoped-vocabulary catalog and seed it. Empty/missing asset
/// is a no-op (the interview simply falls back to generic flow suggestions).
Future<void> _seedScopedVocab(NexusDatabase db) async {
  // Already seeded — skip loading/parsing the (large) catalog asset entirely.
  if (await db.hasSetupScopes()) return;
  String raw;
  try {
    raw = await rootBundle.loadString('assets/setup/scoped_vocab.json');
  } catch (_) {
    return; // asset not bundled
  }
  if (raw.trim().isEmpty) return;
  final decoded = jsonDecode(raw);
  if (decoded is! List || decoded.isEmpty) return;
  await db.seedSetupScopes(decoded);
}

Future<void> _maybeCreateDefaults(NexusDatabase db) async {
  final existingDefault = await db.getDefaultClient();
  if (existingDefault != null) return; // Already have a Default client.

  try {
    // Seeds the Default client + a Local Lemonade server + skill prefabs + the
    // default agent pack (Application Development).
    await db.createClientWithDefaults(name: 'Default', isDefault: true);
  } catch (e) {
    debugPrint('Seeder: could not ensure Default client (non-fatal): $e');
  }
}
