// Copyright (c) 2026 Geramy Loveless DBA Nexus Projects.
// Author: Geramy Loveless <support@nexus-projects.ai>
// Licensed under the Sustainable Use License. See LICENSE.md.

import '../model/call_system_project.dart';
import '../model/call_flow.dart';
import '../model/call_node.dart';
import '../model/pbx_entities.dart';
import 'call_system_exporter.dart';

/// Maps the portable [CallSystemProject] onto an Asterisk / FreePBX
/// `extensions.conf` dialplan.
///
/// MAPPING STRATEGY
/// ----------------
/// Asterisk's dialplan is imperative: a [context] holds `exten =>` lines, each
/// with a numbered (or labelled) priority that executes top-to-bottom. Our model
/// is a directed graph of [CallNode]s connected by named output ports. We bridge
/// the two like this:
///
///   * Each [CallFlow] becomes one `[context]`. The context name is the flow id,
///     sanitised to the `[A-Za-z0-9_-]` charset Asterisk allows for context
///     names.
///   * Each [CallNode] becomes a labelled extension within that context:
///     `exten => s,1(<nodeId>),Verb(...)`. We hang every node off the special
///     `s` (start) extension and reach nodes by their priority LABEL, so edges
///     become `Goto(context,s,<label>)`. Labels are derived from the node id.
///   * Edges (a node's [CallNode.outputs] port → target node id) compile to
///     `Goto()` to the target node's label. Unconnected ports (null) fall
///     through to a shared `Hangup`.
///   * Menus add per-digit `exten => <digit>,1,Goto(...)` lines alongside the
///     `Background` + `WaitExten` pair, which is exactly how Asterisk IVRs work.
///
/// Anything Asterisk can't natively express (AI voicebot, HTTP request, dial-by-
/// name directory built from our model, sub-flow return semantics) is emitted as
/// a commented stub plus a [notes] caveat so the user isn't misled.
class AsteriskExporter implements CallSystemExporter {
  const AsteriskExporter();

  @override
  String get providerKey => 'asterisk';

  @override
  String get displayName => 'Asterisk (dialplan)';

  @override
  String get artifactExtension => 'conf';

  // ── Naming helpers ──────────────────────────────────────────────────

  /// Asterisk context names accept `[A-Za-z0-9_-]`. Anything else is replaced
  /// with `_` so the generated dialplan parses.
  static String _sanitize(String raw) {
    final cleaned = raw.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '_');
    return cleaned.isEmpty ? 'x' : cleaned;
  }

  /// Per-flow context name, e.g. `flow-main`.
  String _contextName(CallFlow flow) => 'flow-${_sanitize(flow.id)}';

  /// Priority label for a node (used as `1(<label>)` and `Goto` target). Labels
  /// share the context's sanitisation rules.
  String _nodeLabel(CallNode node) => 'n_${_sanitize(node.id)}';

  /// Macro/feature contexts we emit alongside the flow contexts.
  static const String _ringGroupsContext = 'nexus-ring-groups';
  static const String _queuesContext = 'nexus-queues';
  static const String _inboundContext = 'from-pstn';

  // ── Escaping ────────────────────────────────────────────────────────

  /// Asterisk treats `,` `|` and `;` specially inside application arguments
  /// (`;` starts a comment, `,` separates args). For prompt text used in a
  /// `Verbose`/comment we strip newlines and neutralise `;`. For real audio we
  /// never inline text — see [_playPromptLines].
  static String _escapeArg(String raw) =>
      raw.replaceAll('\n', ' ').replaceAll('\r', ' ').replaceAll(';', ',');

  /// Comment-safe text (a `;` line can contain anything but newlines).
  static String _escapeComment(String raw) =>
      raw.replaceAll('\n', ' ').replaceAll('\r', ' ');

  // ── Entry point ─────────────────────────────────────────────────────

  @override
  Map<String, String> export(CallSystemProject project) {
    final b = StringBuffer();

    _writeHeader(b, project);
    _writeInboundContext(b, project);
    _writeRingGroups(b, project);
    _writeQueues(b, project);

    for (final flow in project.flows) {
      _writeFlowContext(b, project, flow);
    }

    return {'extensions.conf': b.toString()};
  }

  // ── File header ─────────────────────────────────────────────────────

  void _writeHeader(StringBuffer b, CallSystemProject project) {
    b.writeln('; ============================================================');
    b.writeln('; Asterisk dialplan generated by Nexus Projects.');
    b.writeln('; Project: ${_escapeComment(project.name)}');
    b.writeln('; Sub-category: ${project.subCategory.name}');
    b.writeln('; Experience mode: ${_escapeComment(project.experienceMode)}');
    if (project.isOutbound) {
      b.writeln(';');
      b.writeln('; NOTE: outbound project — ensure TCPA/consent/DNC compliance');
      b.writeln(';       and an appropriate trunk/CallerID are configured.');
    }
    b.writeln('; ============================================================');
    b.writeln();

    // Surface default flow variables as Asterisk global channel vars so nodes
    // (e.g. ${company}) can reference them. Values are escaped for the conf.
    if (project.variables.isNotEmpty) {
      b.writeln('[globals]');
      for (final entry in project.variables.entries) {
        b.writeln(
            '${_sanitize(entry.key)}=${_escapeArg('${entry.value}')}');
      }
      b.writeln();
    }
  }

  // ── Inbound DID routing ─────────────────────────────────────────────

  /// Maps each managed/unmanaged [Did] to the entry context of its flow. This
  /// is the `from-pstn`/`from-trunk` style context an inbound trunk dials into.
  void _writeInboundContext(StringBuffer b, CallSystemProject project) {
    b.writeln('; ---- Inbound number routing -------------------------------');
    b.writeln('[$_inboundContext]');
    if (project.dids.isEmpty) {
      b.writeln('; (no DIDs defined — wire your trunk to a flow context below)');
    }
    for (final did in project.dids) {
      final label = did.label == null ? '' : ' ; ${_escapeComment(did.label!)}';
      final flow = did.flowId == null ? null : project.flowById(did.flowId!);
      // Asterisk matches on the digits of the dialled number; we use the e164
      // as-is (operators commonly strip the +). The user can tweak the pattern.
      final pattern = _sanitize(did.e164);
      if (flow == null) {
        b.writeln(
            '; DID ${_escapeComment(did.e164)} has no flow — routes nowhere$label');
        b.writeln('exten => $pattern,1,NoOp(Unrouted DID ${_escapeComment(did.e164)})');
        b.writeln(' same => n,Hangup()');
      } else {
        b.writeln('exten => $pattern,1,NoOp(Inbound to ${_escapeComment(flow.name)})$label');
        b.writeln(' same => n,Goto(${_contextName(flow)},s,1)');
      }
    }
    b.writeln();
  }

  // ── Ring groups ─────────────────────────────────────────────────────

  /// Each [RingGroup] becomes a dialable extension that `Dial()`s its members.
  /// Asterisk rings members in parallel when they are joined with `&`, which
  /// matches the ringAll strategy; sequential strategies (hunt etc.) are
  /// approximated and flagged in [notes].
  void _writeRingGroups(StringBuffer b, CallSystemProject project) {
    if (project.ringGroups.isEmpty) return;
    b.writeln('; ---- Ring groups ------------------------------------------');
    b.writeln('[$_ringGroupsContext]');
    for (final rg in project.ringGroups) {
      final ext = rg.number == null ? _sanitize(rg.id) : _sanitize(rg.number!);
      b.writeln('; ${_escapeComment(rg.name)} — strategy ${rg.strategy.name}');
      final dialString = _ringGroupDialString(project, rg);
      b.writeln('exten => $ext,1,NoOp(Ring group ${_escapeComment(rg.name)})');
      if (dialString.isEmpty) {
        b.writeln(' same => n,NoOp(No members in ring group)');
      } else {
        // ringAll: members joined with '&' ring simultaneously.
        // hunt/roundRobin/etc.: Asterisk needs a different construct; we emit
        //  the parallel Dial as a sane default and warn in notes().
        b.writeln(' same => n,Dial($dialString,${rg.ringSeconds})');
      }
      // No-answer failover to a voicemail box, if configured.
      final vmId = rg.failoverVoicemailBoxId;
      if (vmId != null) {
        final vm = _voicemailById(project, vmId);
        if (vm != null) {
          b.writeln(' same => n,VoiceMail(${_voicemailMailbox(vm)},u)');
        }
      }
      b.writeln(' same => n,Hangup()');
    }
    b.writeln();
  }

  /// Builds an Asterisk Dial device string for a ring group's members, joined by
  /// `&` so they ring together: `PJSIP/101&PJSIP/102`.
  String _ringGroupDialString(CallSystemProject project, RingGroup rg) {
    final devices = <String>[];
    for (final extId in rg.extensionIds) {
      final ext = _extensionById(project, extId);
      if (ext != null) devices.add(_dialDevice(ext));
    }
    return devices.join('&');
  }

  // ── Queues ──────────────────────────────────────────────────────────

  /// Each [CallQueue] becomes a dialable extension that hands the caller to the
  /// `Queue()` application. The queue object itself (members, strategy, MOH)
  /// lives in `queues.conf` on Asterisk; we reference it by name and flag that
  /// in [notes].
  void _writeQueues(StringBuffer b, CallSystemProject project) {
    if (project.queues.isEmpty) return;
    b.writeln('; ---- ACD queues -------------------------------------------');
    b.writeln('[$_queuesContext]');
    for (final q in project.queues) {
      final ext = q.number == null ? _sanitize(q.id) : _sanitize(q.number!);
      final queueName = _sanitize(q.id);
      b.writeln(
          '; ${_escapeComment(q.name)} — strategy ${q.strategy.name}, '
          'agents ${q.agentExtensionIds.length}, maxWait ${q.maxWaitSeconds}s');
      b.writeln('exten => $ext,1,NoOp(Queue ${_escapeComment(q.name)})');
      b.writeln(' same => n,Answer()');
      // Queue(<queue>,options,URL,announceoverride,timeout) — pass max wait.
      b.writeln(' same => n,Queue($queueName,t,,,${q.maxWaitSeconds})');
      b.writeln(' same => n,Hangup()');
    }
    b.writeln();
  }

  // ── Flow → context ──────────────────────────────────────────────────

  void _writeFlowContext(
      StringBuffer b, CallSystemProject project, CallFlow flow) {
    b.writeln('; ============================================================');
    b.writeln('; Flow: ${_escapeComment(flow.name)}');
    if (flow.description != null && flow.description!.isNotEmpty) {
      b.writeln('; ${_escapeComment(flow.description!)}');
    }
    b.writeln('; ============================================================');
    b.writeln('[${_contextName(flow)}]');

    final entry = flow.entryNode;
    if (entry == null) {
      b.writeln('; Flow has no entry node.');
      b.writeln('exten => s,1,Hangup()');
      b.writeln();
      return;
    }

    // s,1 jumps to the entry node's label; everything else is reachable via
    // labelled priorities and Goto().
    b.writeln('exten => s,1,NoOp(Enter flow ${_escapeComment(flow.name)})');
    b.writeln(' same => n,Goto(${_nodeLabel(entry)})');
    b.writeln();

    // Emit every node (not just the reachable ones) so manual edits/edges that
    // our walker can't see still resolve to a real label.
    for (final node in flow.nodes) {
      _writeNode(b, project, flow, node);
      b.writeln();
    }

    // Shared fall-through used by unconnected ports.
    b.writeln('exten => s,n($_hangupLabel),Hangup()');
    b.writeln();
  }

  static const String _hangupLabel = 'flow_end';

  /// Goto string for an output port. Falls back to the shared end label when the
  /// port is unconnected (null) or dangling.
  String _gotoFor(CallFlow flow, String? targetId) {
    if (targetId == null) return 'Goto(s,$_hangupLabel)';
    final target = flow.nodeById(targetId);
    if (target == null) return 'Goto(s,$_hangupLabel)';
    return 'Goto(${_nodeLabel(target)})';
  }

  // ── Node → priority chain ───────────────────────────────────────────

  void _writeNode(StringBuffer b, CallSystemProject project, CallFlow flow,
      CallNode node) {
    final label = _nodeLabel(node);
    // First priority of a node carries the (label) so Goto() can target it.
    void first(String app) =>
        b.writeln('exten => s,n($label),$app');
    void next(String app) => b.writeln(' same => n,$app');

    b.writeln('; node ${node.id} [${node.type.key}] ${_escapeComment(node.label)}');

    switch (node.type) {
      case CallNodeType.entry:
        // Entry just answers and proceeds; everything real hangs off it.
        first('NoOp(Entry)');
        next('Answer()');
        next(_gotoFor(flow, node.outputs['next']));
        break;

      case CallNodeType.playPrompt:
        // Playback the prompt audio, then continue. 'next' is the only port.
        final lines = _playPromptLines(project, node, background: false);
        first(lines.isEmpty ? 'NoOp(No prompt)' : lines.first);
        for (final l in lines.skip(1)) {
          next(l);
        }
        next(_gotoFor(flow, node.outputs['next']));
        break;

      case CallNodeType.menu:
        _writeMenuNode(b, project, flow, node);
        break;

      case CallNodeType.gatherDigits:
        // Read(<var>,<file>,<maxdigits>) collects DTMF into a channel variable.
        final variable = _sanitize('${node.config['variable'] ?? 'digits'}');
        final promptFile = _promptFile(project, node);
        final maxDigits = '${node.config['maxDigits'] ?? ''}';
        first('NoOp(Gather digits -> $variable)');
        next('Read($variable,$promptFile,$maxDigits)');
        // 'next' on success; 'timeout' if nothing was entered.
        next('GotoIf(\$["\${$variable}" = ""]?'
            '${_gotoTarget(flow, node.outputs['timeout'])}:'
            '${_gotoTarget(flow, node.outputs['next'])})');
        break;

      case CallNodeType.gatherSpeech:
        // Asterisk has no built-in STT; this requires an external speech engine
        // (res_speech / AGI). Emit a stub and a caveat.
        first('NoOp(Speech gather not natively supported — see notes)');
        next('Verbose(1,Gather speech: '
            '${_escapeArg('${node.config['variable'] ?? ''}')})');
        next(_gotoFor(flow, node.outputs['next'] ?? node.outputs['nomatch']));
        break;

      case CallNodeType.aiVoicebot:
        // The conversational AI turn runs in the Nexus managed runtime, not in
        // raw Asterisk. Bridge to an AGI/external-media stub and continue.
        final goal = _escapeArg('${node.config['goal'] ?? ''}');
        first('NoOp(AI voicebot — managed runtime; goal: $goal)');
        next('Verbose(1,AI voicebot placeholder)');
        next(_gotoFor(flow, node.outputs['next'] ?? node.outputs['hangup']));
        break;

      case CallNodeType.dial:
        // Dial an external number over the configured trunk. The user supplies
        // the trunk tech-prefix; we default to PJSIP/<number>@trunk.
        final number = _sanitize('${node.config['number'] ?? ''}');
        first('NoOp(Dial $number)');
        next('Dial(PJSIP/$number,30)');
        // DIALSTATUS routes the result ports.
        next('GotoIf(\$["\${DIALSTATUS}" = "ANSWER"]?'
            '${_gotoTarget(flow, node.outputs['answered'])})');
        next('GotoIf(\$["\${DIALSTATUS}" = "BUSY"]?'
            '${_gotoTarget(flow, node.outputs['busy'])})');
        next('GotoIf(\$["\${DIALSTATUS}" = "NOANSWER"]?'
            '${_gotoTarget(flow, node.outputs['noanswer'])})');
        next(_gotoFor(flow, node.outputs['failed']));
        break;

      case CallNodeType.transferToExtension:
        // Transfer to an internal extension: Dial its device, branch on result.
        final extNumber = '${node.config['extension'] ?? ''}';
        final ext = _extensionByNumber(project, extNumber);
        final device = ext == null
            ? 'PJSIP/${_sanitize(extNumber)}'
            : _dialDevice(ext);
        first('NoOp(Transfer to extension $extNumber)');
        next('Dial($device,${ext?.ringSeconds ?? 20})');
        next('GotoIf(\$["\${DIALSTATUS}" = "ANSWER"]?'
            '${_gotoTarget(flow, node.outputs['answered'])})');
        next('GotoIf(\$["\${DIALSTATUS}" = "BUSY"]?'
            '${_gotoTarget(flow, node.outputs['busy'])})');
        next(_gotoFor(flow, node.outputs['noanswer']));
        break;

      case CallNodeType.ringGroup:
        // Hand off to the ring-group context entry, then branch on result.
        final rgId = '${node.config['ringGroupId'] ?? node.config['number'] ?? ''}';
        final rg = _ringGroupByIdOrNumber(project, rgId);
        first('NoOp(Ring group $rgId)');
        if (rg != null) {
          final ds = _ringGroupDialString(project, rg);
          if (ds.isNotEmpty) {
            next('Dial($ds,${rg.ringSeconds})');
          } else {
            next('NoOp(Ring group has no members)');
          }
        } else {
          next('NoOp(Unknown ring group $rgId)');
        }
        next('GotoIf(\$["\${DIALSTATUS}" = "ANSWER"]?'
            '${_gotoTarget(flow, node.outputs['answered'])})');
        next(_gotoFor(flow, node.outputs['noanswer']));
        break;

      case CallNodeType.queue:
        // Place the caller into an ACD queue (queues.conf object).
        final qId = '${node.config['queueId'] ?? node.config['number'] ?? ''}';
        final q = _queueByIdOrNumber(project, qId);
        final queueName = q == null ? _sanitize(qId) : _sanitize(q.id);
        first('NoOp(Queue $qId)');
        next('Answer()');
        next('Queue($queueName,t,,,${q?.maxWaitSeconds ?? 300})');
        // After Queue returns, QUEUESTATUS tells us why.
        next('GotoIf(\$["\${QUEUESTATUS}" = "TIMEOUT"]?'
            '${_gotoTarget(flow, node.outputs['timeout'])})');
        next('GotoIf(\$["\${QUEUESTATUS}" = "JOINEMPTY"]?'
            '${_gotoTarget(flow, node.outputs['empty'])})');
        next(_gotoFor(flow, node.outputs['answered']));
        break;

      case CallNodeType.voicemail:
        // Send caller to a mailbox. 'done' continues after the message.
        final vmId = '${node.config['voicemailBoxId'] ?? node.config['mailbox'] ?? ''}';
        final vm = _voicemailByIdOrNumber(project, vmId);
        final mailbox = vm == null ? _sanitize(vmId) : _voicemailMailbox(vm);
        first('NoOp(Voicemail $mailbox)');
        next('VoiceMail($mailbox,u)');
        next(_gotoFor(flow, node.outputs['done']));
        break;

      case CallNodeType.schedule:
        // Branch on a TimeCondition. We compile the open ranges into GotoIfTime.
        _writeScheduleNode(b, project, flow, node);
        break;

      case CallNodeType.condition:
        // Branch on an expression in config['expression'] (or a variable).
        final expr = '${node.config['expression'] ?? node.config['variable'] ?? '1'}';
        first('NoOp(Condition)');
        next('GotoIf(\$[${_escapeArg(expr)}]?'
            '${_gotoTarget(flow, node.outputs['true'])}:'
            '${_gotoTarget(flow, node.outputs['false'])})');
        break;

      case CallNodeType.setVariable:
        // Assign a channel variable.
        final variable = _sanitize('${node.config['variable'] ?? 'var'}');
        final value = _escapeArg('${node.config['value'] ?? ''}');
        first('Set($variable=$value)');
        next(_gotoFor(flow, node.outputs['next']));
        break;

      case CallNodeType.httpRequest:
        // CURL() can fetch a URL; complex request shaping needs AGI. We do a
        // best-effort GET and flag richer cases in notes().
        final url = _escapeArg('${node.config['url'] ?? ''}');
        final into = _sanitize('${node.config['variable'] ?? 'httpResult'}');
        first('NoOp(HTTP request -> $into)');
        next('Set($into=\${CURL($url)})');
        // success if we got a non-empty body, else failure.
        next('GotoIf(\$["\${$into}" != ""]?'
            '${_gotoTarget(flow, node.outputs['success'])}:'
            '${_gotoTarget(flow, node.outputs['failure'])})');
        break;

      case CallNodeType.record:
        // Record the caller; honour recording-consent rules out of band.
        final file = _sanitize('${node.config['file'] ?? node.id}');
        first('NoOp(Record call)');
        next('Record($file:wav)');
        next(_gotoFor(flow, node.outputs['next']));
        break;

      case CallNodeType.playDirectory:
        // Dial-by-name directory. Asterisk's Directory() reads voicemail.conf
        // names; our model's extensions feed that. Branch on match.
        first('NoOp(Dial-by-name directory)');
        next('Directory(default,${_contextName(flow)})');
        next(_gotoFor(flow, node.outputs['matched'] ?? node.outputs['nomatch']));
        break;

      case CallNodeType.hangup:
        first('Hangup()');
        break;

      case CallNodeType.subFlow:
        // Gosub into the sub-flow's context; on return continue at 'returned'.
        final subId = '${node.config['flowId'] ?? ''}';
        final sub = project.flowById(subId);
        first('NoOp(Sub-flow $subId)');
        if (sub != null) {
          // Goto the sub-flow context start. True Gosub/return needs the sub to
          // Return(); we flag that nuance in notes().
          next('Goto(${_contextName(sub)},s,1)');
        } else {
          next('NoOp(Unknown sub-flow $subId)');
          next(_gotoFor(flow, node.outputs['returned']));
        }
        break;
    }
  }

  // ── Menu node ───────────────────────────────────────────────────────

  /// IVR menu: `Background` (plays prompt while accepting DTMF) + `WaitExten`,
  /// then per-digit `exten => <digit>` matches that Goto the branch target. The
  /// digit ports are the extra (non-base) keys in [CallNode.outputs].
  void _writeMenuNode(StringBuffer b, CallSystemProject project, CallFlow flow,
      CallNode node) {
    final label = _nodeLabel(node);
    final promptFile = _promptFile(project, node);
    final timeoutSecs = '${node.config['timeout'] ?? 5}';

    b.writeln('exten => s,n($label),NoOp(Menu ${_escapeComment(node.label)})');
    b.writeln(' same => n,Background($promptFile)');
    b.writeln(' same => n,WaitExten($timeoutSecs)');

    // Base ports for a menu are 'timeout' and 'invalid'; every OTHER key in
    // outputs is a DTMF digit branch.
    final basePorts = CallNodeType.menu.basePorts.toSet();
    for (final entry in node.outputs.entries) {
      if (basePorts.contains(entry.key)) continue;
      final digit = entry.key;
      // A digit branch is its own matched extension in this context that simply
      // Goto()s the target node's label.
      b.writeln(
          'exten => ${_sanitize(digit)},1,${_gotoFor(flow, entry.value)}');
    }

    // Asterisk's reserved 't' (timeout) and 'i' (invalid) extensions.
    b.writeln('exten => t,1,${_gotoFor(flow, node.outputs['timeout'])}');
    b.writeln('exten => i,1,${_gotoFor(flow, node.outputs['invalid'])}');
  }

  // ── Schedule node ───────────────────────────────────────────────────

  /// Compiles a [TimeCondition] into `GotoIfTime` lines. Asterisk's GotoIfTime
  /// takes `<time>,<weekdays>,<monthdays>,<months>`. We translate each open
  /// [TimeRange]; the first matching range routes to 'open', holidays route to
  /// 'holiday', everything else to 'closed'.
  void _writeScheduleNode(StringBuffer b, CallSystemProject project,
      CallFlow flow, CallNode node) {
    final label = _nodeLabel(node);
    final tcId = '${node.config['timeConditionId'] ?? node.config['scheduleId'] ?? ''}';
    final tc = _timeConditionById(project, tcId);

    b.writeln('exten => s,n($label),NoOp(Schedule ${_escapeComment(node.label)})');

    if (tc == null) {
      b.writeln(' same => n,NoOp(Unknown time condition $tcId)');
      b.writeln(' same => n,${_gotoApp(flow, node.outputs['closed'])}');
      return;
    }

    // Holidays first: GotoIfTime matches a specific date via month/day fields.
    for (final iso in tc.holidayDates) {
      final parts = iso.split('-'); // yyyy-MM-dd
      if (parts.length == 3) {
        final month = _monthName(int.tryParse(parts[1]));
        final day = int.tryParse(parts[2]);
        if (month != null && day != null) {
          b.writeln(' same => n,GotoIfTime(*,*,$day,$month?'
              '${_gotoTarget(flow, node.outputs['holiday'])})');
        }
      }
    }

    // Open ranges → 'open'.
    for (final r in tc.openRanges) {
      final time = '${_hhmm(r.startMinute)}-${_hhmm(r.endMinute)}';
      final dow = _weekdays(r.days);
      b.writeln(' same => n,GotoIfTime($time,$dow,*,*?'
          '${_gotoTarget(flow, node.outputs['open'])})');
    }

    // Fall through = closed.
    b.writeln(' same => n,${_gotoApp(flow, node.outputs['closed'])}');
  }

  // ── Prompt helpers ──────────────────────────────────────────────────

  /// Resolves a node's prompt and produces the playback line(s). When the prompt
  /// has a recorded audio asset we reference that file; for TTS-only prompts we
  /// reference a conventional file path AND emit the text as a comment so the
  /// operator knows what to synthesise/record.
  List<String> _playPromptLines(
      CallSystemProject project, CallNode node, {required bool background}) {
    final promptId = node.config['promptId'];
    if (promptId == null) return const [];
    final prompt = project.promptById('$promptId');
    if (prompt == null) {
      return ['NoOp(Missing prompt $promptId)'];
    }
    final file = _promptFileFor(prompt);
    final verb = background ? 'Background' : 'Playback';
    final lines = <String>[];
    if (prompt.text.isNotEmpty) {
      // Comment carries the spoken text for the operator (escaped, single line).
      lines.add('NoOp(Say: ${_escapeArg(prompt.text)})');
    }
    lines.add('$verb($file)');
    return lines;
  }

  /// The Asterisk sound file token for a node's configured prompt (no extension;
  /// Asterisk appends the codec extension). Falls back to a per-node token.
  String _promptFile(CallSystemProject project, CallNode node) {
    final promptId = node.config['promptId'];
    if (promptId != null) {
      final prompt = project.promptById('$promptId');
      if (prompt != null) return _promptFileFor(prompt);
    }
    return 'nexus/${_sanitize(node.id)}';
  }

  /// Sound-file token for a [Prompt]. Recorded assets keep their relative path
  /// (sans extension); TTS prompts get a conventional `nexus/<id>` token.
  String _promptFileFor(Prompt prompt) {
    final asset = prompt.audioAssetPath;
    if (asset != null && asset.isNotEmpty) {
      // Strip a trailing extension — Asterisk wants the basename only.
      final dot = asset.lastIndexOf('.');
      final base = dot > 0 ? asset.substring(0, dot) : asset;
      return base;
    }
    return 'nexus/${_sanitize(prompt.id)}';
  }

  // ── Goto / target string helpers ────────────────────────────────────

  /// The bare `context,exten,prio`-style target for use INSIDE a GotoIf ternary
  /// (no `Goto(...)` wrapper). Unconnected → the flow end label.
  String _gotoTarget(CallFlow flow, String? targetId) {
    if (targetId == null) return 's,$_hangupLabel';
    final target = flow.nodeById(targetId);
    if (target == null) return 's,$_hangupLabel';
    return 's,${_nodeLabel(target)}';
  }

  /// A full `Goto(...)` application for a port (used as a standalone priority).
  String _gotoApp(CallFlow flow, String? targetId) =>
      _gotoFor(flow, targetId);

  // ── Entity lookups ──────────────────────────────────────────────────

  Extension? _extensionById(CallSystemProject project, String id) {
    for (final e in project.extensions) {
      if (e.id == id) return e;
    }
    return null;
  }

  Extension? _extensionByNumber(CallSystemProject project, String number) {
    for (final e in project.extensions) {
      if (e.number == number) return e;
    }
    return _extensionById(project, number);
  }

  VoicemailBox? _voicemailById(CallSystemProject project, String id) {
    for (final v in project.voicemailBoxes) {
      if (v.id == id) return v;
    }
    return null;
  }

  VoicemailBox? _voicemailByIdOrNumber(CallSystemProject project, String key) {
    for (final v in project.voicemailBoxes) {
      if (v.id == key || v.mailboxNumber == key) return v;
    }
    return null;
  }

  RingGroup? _ringGroupByIdOrNumber(CallSystemProject project, String key) {
    for (final r in project.ringGroups) {
      if (r.id == key || r.number == key) return r;
    }
    return null;
  }

  CallQueue? _queueByIdOrNumber(CallSystemProject project, String key) {
    for (final q in project.queues) {
      if (q.id == key || q.number == key) return q;
    }
    return null;
  }

  TimeCondition? _timeConditionById(CallSystemProject project, String id) {
    for (final t in project.timeConditions) {
      if (t.id == id) return t;
    }
    return null;
  }

  /// Asterisk device string for an extension. Prefers an explicit SIP username,
  /// else the dial number, over PJSIP.
  String _dialDevice(Extension ext) {
    final user = (ext.sipUsername != null && ext.sipUsername!.isNotEmpty)
        ? ext.sipUsername!
        : ext.number;
    return 'PJSIP/${_sanitize(user)}';
  }

  /// VoiceMail() mailbox token. Prefers the explicit mailbox number, else the
  /// box id, in the `default` context.
  String _voicemailMailbox(VoicemailBox vm) {
    final box = (vm.mailboxNumber != null && vm.mailboxNumber!.isNotEmpty)
        ? vm.mailboxNumber!
        : vm.id;
    return '${_sanitize(box)}@default';
  }

  // ── Time helpers ────────────────────────────────────────────────────

  /// minutes-from-midnight → `HH:MM` for GotoIfTime.
  String _hhmm(int minute) {
    final h = (minute ~/ 60).clamp(0, 23);
    final m = (minute % 60).clamp(0, 59);
    final hh = h.toString().padLeft(2, '0');
    final mm = m.toString().padLeft(2, '0');
    return '$hh:$mm';
  }

  /// Our days are 1=Mon..7=Sun. Asterisk GotoIfTime uses mon,tue,...,sun and
  /// accepts ranges; we emit a comma list of the three-letter day names.
  String _weekdays(List<int> days) {
    const names = {
      1: 'mon',
      2: 'tue',
      3: 'wed',
      4: 'thu',
      5: 'fri',
      6: 'sat',
      7: 'sun',
    };
    final out = days.map((d) => names[d]).whereType<String>().toList();
    return out.isEmpty ? '*' : out.join('&');
  }

  /// Asterisk month token (jan..dec) from a 1..12 month number.
  String? _monthName(int? m) {
    const names = [
      'jan', 'feb', 'mar', 'apr', 'may', 'jun',
      'jul', 'aug', 'sep', 'oct', 'nov', 'dec',
    ];
    if (m == null || m < 1 || m > 12) return null;
    return names[m - 1];
  }

  // ── Caveats ─────────────────────────────────────────────────────────

  @override
  List<String> notes(CallSystemProject project) {
    final out = <String>[
      'Queues reference a queues.conf object by name; you must define each '
          'queue (members, strategy, music-on-hold) in queues.conf — only the '
          'dialplan entry point is generated here.',
      'Voicemail boxes reference mailboxes in the "default" context of '
          'voicemail.conf; provision the mailboxes and greetings there.',
      'SIP/PJSIP device names are derived from each extension\'s sipUsername '
          '(or dial number); confirm they match your pjsip.conf endpoints.',
      'Inbound DID patterns in [$_inboundContext] use the raw E.164 digits; '
          'adjust to match what your trunk delivers (some strip the leading +).',
    ];

    // Ring strategies other than ringAll are approximated as a parallel Dial.
    final nonRingAll = project.ringGroups
        .where((r) => r.strategy != RingStrategy.ringAll)
        .map((r) => r.name)
        .toList();
    if (nonRingAll.isNotEmpty) {
      out.add('Ring groups ${nonRingAll.join(', ')} use a sequential/rotating '
          'strategy (${'hunt/roundRobin/etc.'}); Asterisk dialplan rings them '
          'in parallel here. Use a hunt-group construct (e.g. dialplan loops or '
          'FreePBX ring groups) for true sequential behaviour.');
    }

    // Detect node types Asterisk can't natively express across all flows.
    final hasSpeech = _anyNode(project, CallNodeType.gatherSpeech);
    final hasAi = _anyNode(project, CallNodeType.aiVoicebot);
    final hasHttp = _anyNode(project, CallNodeType.httpRequest);
    final hasSubFlow = _anyNode(project, CallNodeType.subFlow);

    if (hasSpeech) {
      out.add('gatherSpeech nodes need an external speech-recognition engine '
          '(res_speech/AGI); the generated dialplan only stubs them.');
    }
    if (hasAi) {
      out.add('aiVoicebot nodes run in the Nexus managed runtime (streamed '
          'STT/LLM/TTS); the dialplan emits a placeholder — bridge via AGI/'
          'external media to enable them on raw Asterisk.');
    }
    if (hasHttp) {
      out.add('httpRequest nodes use CURL() for a best-effort GET; POST bodies, '
          'headers and JSON parsing require AGI or func_curl configuration.');
    }
    if (hasSubFlow) {
      out.add('subFlow nodes Goto the sub-flow context without a true return; '
          'for call/return semantics convert them to Gosub()/Return() manually.');
    }

    if (project.isOutbound) {
      out.add('This is an outbound project: configure an outbound trunk and '
          'CallerID, and ensure TCPA/consent/DNC compliance before dialing.');
    }

    return out;
  }

  bool _anyNode(CallSystemProject project, CallNodeType type) {
    for (final flow in project.flows) {
      for (final node in flow.nodes) {
        if (node.type == type) return true;
      }
    }
    return false;
  }
}
